server: 
  port: 8899
record: 
  log: 
    storageType: database  
    filePath: rr.log
spring: 
  datasource: 
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver